#! /bin/bash
comentario(){ printf "\033[0;34m#\033[0m";}
echo -e "[0;34m#Executa o script new_alias.sh[0m"
echo -e "alias new_alias=\"$SCRIPTS/new_alias.sh\""
echo -e "[0;34m#Edita o script new_alias.sh[0m"
echo -e "alias edit_new_alias=\"sudo nano $SCRIPTS/new_alias.sh\""
echo -e "[0;34m#Executa o script my_alias[0m"
echo -e "alias my_alias=\"$SCRIPTS/my_alias.sh\""
echo -e "[0;34m#Edita o script my_alias[0m"
echo -e "alias edit_my_alias=\"sudo nano $SCRIPTS/my_alias.sh\""
echo -e "[0;34m#Executa o script eblood_start.sh[0m"
echo -e "alias eblood_start=\"$SCRIPTS/eblood_start.sh\""
echo -e "[0;34m#Edita o script eblood_start.sh[0m"
echo -e "alias edit_eblood_start=\"sudo nano $SCRIPTS/eblood_start.sh\""
echo -e "[0;34m#Executa o script eblood_client.sh[0m"
echo -e "alias eblood_client=\"$SCRIPTS/eblood_client.sh\""
echo -e "[0;34m#Edita o script eblood_client.sh[0m"
echo -e "alias edit_eblood_client=\"sudo nano $SCRIPTS/eblood_client.sh\""
echo -e "[0;34m##Edita o script new_database[0m"
echo -e "alias edit_new_database=\"sudo nano $SCRIPTS/new_database.sh\""
echo -e "[0;34m#Executa o script new_database.sh[0m"
echo -e "alias new_database=\"$SCRIPTS/new_database.sh\""
